### ISSUE TITLE
Creating Applications

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-webserver#10]
- [x] Endpoint exposing application creation within an account over HTTP
- [x] Endpoint exposing application key for a created application over HTTP
- [x] Application creation creates a default cluster

**Comment by robinsdm** [comment]
No work is currently done. Moving to sprint 5 so that we know how security will work, before working on this.

**Comment by aj-michael** [comment]
@robinsdm What is the status of this? This is blocking the pathfinder-server work on application socket endpoints which in turn is blocking the iOS sdk work.

**Comment by robinsdm** [comment]
Basically, all the endpoints needs is the application's ID. From there it will handle auth with the users session.

**Comment by aj-michael** [comment]
Where is the code that does this? Do you have a PR? I'd like to get default clusters by application ID into the dev branch ASAP so that we can expose a server socket endpoint that allows you to get default cluster by application ID. I believe this is the primary use case of our service.

**Comment by aj-michael** [comment]
@robinsdm Can you please update this issue? Was this the PR that Dan merged in yesterday? #14

**Comment by robinsdm** [comment]
It should be completed as of the last merge.

**Comment by robinsdm** [comment]
It took 7 hours.
