### ISSUE TITLE
Application cluster endpoint

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-webserver#11]
- [ ] Endpoint exposing clusters for application over HTTP
- [ ] API Documentation for cluster endpoint

**Comment by robinsdm** [comment]
No work is currently done. Moving to sprint 5 so that we know how security will work, before working on this.

**Comment by aj-michael** [comment]
I think we've determined that this is the responsibility of pathfinder-webserver. Closing this issue and moving it there.
