### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-webserver#12]
- [ ] Increase test coverage to 60%

**Comment by robinsdm** [comment]
This will be pushed to later. Until we know what code will be kept.

**Comment by aj-michael** [comment]
@robinsdm I've modified the issue to a level that is on par with our other server.

**Comment by aj-michael** [comment]
Not measuring test coverage on webserver because the mission critical logic is in pathfinder server.
