### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-webserver#5]
- [x] Developer can create new account
- [x] Developer can sign in

**Comment by aj-michael** [comment]
Related to https://github.com/CSSE497/pathfinder-webclient/issues/1

**Comment by robinsdm** [comment]
It's being worked on now. Basic support might be done tomorrow.

**Comment by aj-michael** [comment]
@robinsdm: How long did this take you? And how long do you think it will blend into next sprint?

**Comment by robinsdm** [comment]
It took a while to finish this because of data validation not being supported any more. Registration will roll over to next sprint. So far it has taken me about 6 hours and hopefully it will be done with another two hours of work, once we locked down how registration will need to work.
